import os
import json
import argparse
from pathlib import Path

# --- CORE CONFIGURATION & SETUP ---
RESEARCH_DIR = "outputs/research"

TEMPLATE_HEADER = """# Auto-Generated by auto_scaffold_from_research.py
# File: {path}
# Purpose: {purpose}

"""

BASIC_README = """# {agent_name}

## Purpose
{summary}

## Best Tools
{tools}

## Model Strategy
{models}

## Setup
- Add env vars to `.env` as listed below.
- Run the CLI examples to test the agent.

## Env Vars
{envs}

## CLI
{clis}
"""

def sanitize(text: str) -> str:
    return (text or "").strip()

def ensure_parent(path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)

def write_file_if_absent(path: Path, content: str):
    if path.exists():
        print(f"[SKIP] Exists → {path}")
        return
    ensure_parent(path)
    path.write_text(content, encoding="utf-8")
    print(f"[OK] Wrote → {path}")

def build_readme(agent_name, spec):
    tools = "\n".join([f"- **{t.get('name','')}** — {t.get('why','')}" for t in spec.get("best_tools",[])])
    models = "\n".join([f"- **{m.get('task','')}** → {m.get('model','')} ({m.get('settings','')})" for m in spec.get("model_strategy",[])])
    envs = "\n".join([f"- `{e}`" for e in spec.get("build_spec",{}).get("env_vars",[])])
    clis = "\n".join([f"```bash\n{c}\n```" for c in spec.get("build_spec",{}).get("cli_examples",[])])
    return BASIC_README.format(
        agent_name=agent_name,
        summary=sanitize(spec.get("executive_summary","")),
        tools=tools or "(none listed)",
        models=models or "(none listed)",
        envs=envs or "(none listed)",
        clis=clis or "(none)"
    )

def main():
    ap = argparse.ArgumentParser(description="Scaffold files from a research JSON spec")
    ap.add_argument("--spec", required=False, help="Path to research JSON (default: latest in outputs/research)")
    args = ap.parse_args()

    # locate spec
    if args.spec and os.path.exists(args.spec):
        spec_path = args.spec
    else:
        # pick latest json in RESEARCH_DIR
        files = sorted([p for p in Path(RESEARCH_DIR).glob("*.json")], key=lambda p: p.stat().st_mtime, reverse=True)
        if not files:
            print("[FATAL ERROR] No research JSON found. Run: python x10_orchestrator.py")
            return
        spec_path = str(files[0])

    with open(spec_path, "r", encoding="utf-8") as f:
        spec = json.load(f)

    agent_name = sanitize(spec.get("build_spec",{}).get("agent_name", "")) or "New Agent"
    files = spec.get("build_spec",{}).get("files",[])
    envs  = spec.get("build_spec",{}).get("env_vars",[])
    clis  = spec.get("build_spec",{}).get("cli_examples",[])

    # 1) README
    readme_path = Path(f"core/agents/{agent_name.lower().replace(' ','_')}/README.md")
    write_file_if_absent(readme_path, build_readme(agent_name, spec))

    # 2) files from spec
    for f in files:
        path = Path(f.get("path","")).as_posix()
        purpose = sanitize(f.get("purpose",""))
        if not path:
            continue
        stub = TEMPLATE_HEADER.format(path=path, purpose=purpose)
        write_file_if_absent(Path(path), stub)

    # 3) env template
    if envs:
        env_sample = "\n".join([e.split("=")[0]+"=REPLACE_ME" for e in envs])
        write_file_if_absent(Path(f"core/agents/{agent_name.lower().replace(' ','_')}/.env.sample"), env_sample)

    # 4) manifest
    manifest = {
        "agent": agent_name,
        "spec_source": spec_path,
        "created_files": [f.get("path","") for f in files],
        "env_vars": envs,
        "cli_examples": clis
    }
    write_file_if_absent(Path(f"core/agents/{agent_name.lower().replace(' ','_')}/manifest.json"), json.dumps(manifest, indent=2))
    print("[SUCCESS] Scaffold complete.")

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"[FATAL ERROR] {e}")
